
import React, { useEffect } from "react";
import { Stack, useRouter } from "expo-router";
import * as Linking from "expo-linking";

import { AuthProvider } from "../context/AuthContext";
import {
    NetworkStatusProvider
} from "../context/NetworkStatusContext";
import { completeTrainingFromUnity } from "../services/trainingResultService";

export default function RootLayout() {
    const router = useRouter();

    useEffect(() => {
        const handleDeepLink = async (event) => {
            try {
                const url = event?.url;

                if (!url) {
                    return;
                }

                console.log(
                    "[DeepLink] Received:",
                    url
                );

                const parsed = Linking.parse(url);

                console.log(
                    "[DeepLink] Parsed:",
                    parsed
                );

                const path = parsed?.path;
                const params = parsed?.queryParams || {};

                // =====================================================
                // CERTIFICATE VERIFICATION DEEP LINK
                // =====================================================
                //
                // Example:
                //
                // sih26041app://verify-certificate
                //     ?certificateId=SIH-12345
                //
                // This is generated by the certificate QR code.
                //

                if (path === "verify-certificate") {
                    const certificateId =
                        params.certificateId;

                    console.log(
                        "[CertificateQR] Certificate ID:",
                        certificateId
                    );

                    if (!certificateId) {
                        console.error(
                            "[CertificateQR] Certificate ID missing."
                        );

                        return;
                    }

                    router.push({
                        pathname: "/verify-certificate",
                        params: {
                            certificateId:
                                String(certificateId)
                        }
                    });

                    return;
                }

                // =====================================================
                // UNITY TRAINING RESULT DEEP LINK
                // =====================================================

                if (path !== "training-result") {
                    console.log(
                        "[DeepLink] Ignoring unrelated deep link."
                    );

                    return;
                }

                console.log(
                    "[TrainingResult] Deep link received:",
                    url
                );

                // --------------------------------
                // Get data sent by Unity
                // --------------------------------

                const attemptId = params.attemptId;
                const moduleId = params.moduleId;
                const score = Number(params.score);
                const result = params.result;

                // --------------------------------
                // Parse mistakes
                // --------------------------------

                let mistakes = [];

                if (params.mistakes) {
                    try {
                        mistakes =
                            typeof params.mistakes ===
                            "string"
                                ? JSON.parse(
                                      params.mistakes
                                  )
                                : params.mistakes;
                    } catch (error) {
                        console.warn(
                            "[TrainingResult] Could not parse mistakes:",
                            error
                        );

                        mistakes = [];
                    }
                }

                // --------------------------------
                // Debug logs
                // --------------------------------

                console.log(
                    "[TrainingResult] Attempt ID:",
                    attemptId
                );

                console.log(
                    "[TrainingResult] Module ID:",
                    moduleId
                );

                console.log(
                    "[TrainingResult] Score:",
                    score
                );

                console.log(
                    "[TrainingResult] Result:",
                    result
                );

                console.log(
                    "[TrainingResult] Mistakes:",
                    mistakes
                );

                // --------------------------------
                // Validate data
                // --------------------------------

                if (
                    !attemptId ||
                    !moduleId ||
                    !Number.isFinite(score) ||
                    !result
                ) {
                    console.error(
                        "[TrainingResult] Missing or invalid result data.",
                        {
                            attemptId,
                            moduleId,
                            score,
                            result
                        }
                    );

                    return;
                }

                // --------------------------------
                // Send Unity result to backend
                // --------------------------------

                const response =
                    await completeTrainingFromUnity(
                        attemptId,
                        score,
                        result,
                        mistakes
                    );

                console.log(
                    "[TrainingResult] Backend response:",
                    response
                );

                // --------------------------------
                // After backend update
                // --------------------------------

                if (response?.success) {
                    console.log(
                        "[TrainingResult] Training attempt completed successfully."
                    );

                    // If scenario passed,
                    // open assessment
                    if (result === "passed") {
                        console.log(
                            "[TrainingResult] Opening assessment..."
                        );

                        router.replace({
                            pathname:
                                "/worker/assessment/[moduleId]",
                            params: {
                                moduleId:
                                    moduleId,
                                attemptId:
                                    attemptId
                            }
                        });
                    } else {
                        // Training failed
                        console.log(
                            "[TrainingResult] Training failed. Returning to dashboard."
                        );

                        router.replace(
                            "/worker/dashboard"
                        );
                    }
                }
            } catch (error) {
                console.error(
                    "[DeepLink] Failed to process deep link:",
                    error?.response?.data ||
                        error
                );
            }
        };

        // =====================================================
        // LISTEN FOR DEEP LINKS WHILE APP IS RUNNING
        // =====================================================

        const subscription =
            Linking.addEventListener(
                "url",
                handleDeepLink
            );

        // =====================================================
        // HANDLE DEEP LINK THAT LAUNCHED THE APP
        // =====================================================

        const checkInitialUrl = async () => {
            try {
                const initialUrl =
                    await Linking.getInitialURL();

                if (initialUrl) {
                    console.log(
                        "[DeepLink] Initial URL:",
                        initialUrl
                    );

                    await handleDeepLink({
                        url: initialUrl
                    });
                }
            } catch (error) {
                console.error(
                    "[DeepLink] Failed to get initial URL:",
                    error
                );
            }
        };

        checkInitialUrl();

        // =====================================================
        // CLEANUP
        // =====================================================

        return () => {
            subscription.remove();
        };
    }, [router]);

    return (
      <AuthProvider>
    <NetworkStatusProvider>
        <Stack
            screenOptions={{
                headerShown: false
            }}
        />
    </NetworkStatusProvider>
</AuthProvider>
    );
}

